[platformio]
default_envs = esp32_led_breadboard

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM5
monitor_port = COM5
monitor_dtr = 0
monitor_rts = 0

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.5
    adafruit/Adafruit AHTX0 @ ^2.0.5

[env:esp32_led_breadboard]
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DLED_DATA_PIN=18
    -DLED_COUNT=300
    -DONBOARD_LED_PIN=19
    -DONBOARD_LED_COUNT=3
    -DLED_BRIGHTNESS=32
    -DAHT20_SDA_PIN=21
    -DAHT20_SCL_PIN=22
    -DSWITCH1_PIN=34
    -DSWITCH2_PIN=35
    -DSWITCH3_PIN=36
    -DSWITCH4_PIN=39
    -DFIRMWARE_PROFILE_NAME=\"breadboard\"

[env:esp32_led_pcb]
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DLED_DATA_PIN=18
    -DLED_COUNT=300
    -DONBOARD_LED_PIN=19
    -DONBOARD_LED_COUNT=3
    -DLED_BRIGHTNESS=32
    -DAHT20_SDA_PIN=21
    -DAHT20_SCL_PIN=22
    -DSWITCH1_PIN=34
    -DSWITCH2_PIN=35
    -DSWITCH3_PIN=36
    -DSWITCH4_PIN=39
    -DFIRMWARE_PROFILE_NAME=\"pcb\"
